sudo: required
services:
  - docker

before_install:
  - docker build -t richard357/docker-react:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true richard357/docker-react:latest npm run test